### ISSUE TITLE
Queue EasyNetQ_Default_Error_Queue

### ISSUE THREAD

**Issue by wtujvk** [SFLAQiu/RabbitMQDemo#1]
怎么发送Queue EasyNetQ_Default_Error_Queue里面的消息?

**Comment by SFLAQiu** [comment]
如果订阅回调引发异常，则EasyNetQ将接收正在使用的消息并将其包含在特殊的错误消息中。 该错误消息将发布到EasyNetQ错误队列（名为EasyNetQ_Default_Error_Queue）
你要主动发布消息到EasyNetQ_Default_Error_Queue做什么？
